# Generated by Django 2.2.4 on 2019-08-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0008_auto_20190818_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='moderation',
            new_name='approved_comment',
        ),
    ]
