# Generated by Django 2.2.3 on 2019-08-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0010_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
