# Generated by Django 2.2.3 on 2019-08-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0011_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
