# Generated by Django 2.2.4 on 2019-08-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0014_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
