# Generated by Django 2.2.4 on 2019-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0018_auto_20190829_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.CharField(max_length=200),
        ),
    ]
