# Generated by Django 2.2.4 on 2019-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0021_auto_20190903_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
