# Generated by Django 2.2.4 on 2019-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_net', '0022_auto_20190903_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
